spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/device_management
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false

mqtt:
  broker-url: tcp://mqtt:1883
  client-id: device-service-docker
  topic: devices/events

logging:
  level:
    com.example.devicemanagement: INFO
    org.springframework: INFO